# Generated by Django 6.1.1 on 2026-09-07 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_category_project_challenges_project_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-completed_date', '-created_at', 'title']},
        ),
        migrations.AddField(
            model_name='project',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Project cost in KSh.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='pages',
            field=models.PositiveIntegerField(default=1, help_text='Number of pages/screens in the project.'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, help_text='Example: E-Commerce, Business Website, Web Application', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, help_text='Example: 4 weeks, 2 months', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Main project image.', null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, help_text='Example: Full-Stack Developer', max_length=200),
        ),
    ]
