# Generated by Django 6.1.1 on 2026-09-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_options_project_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_cost',
            field=models.BooleanField(default=False, help_text='If enabled, the project cost will be displayed publicly.'),
        ),
    ]
