# Generated by Django 6.1.1 on 2026-09-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_show_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Calvin Ochieng', max_length=150)),
                ('professional_title', models.CharField(default='Software Developer & Web Solutions', max_length=200)),
                ('short_bio', models.TextField(blank=True, default='I build modern websites, web applications and digital solutions that help businesses work better.')),
                ('photo', models.ImageField(blank=True, help_text='Upload your professional profile photo.', null=True, upload_to='profile/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, default='Kenya', max_length=150)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Profile',
                'verbose_name_plural': 'Site Profile',
            },
        ),
    ]
